### ISSUE TITLE
HML Spec: phasing in order to resolve ambiguity of Exon shuffling

### ISSUE THREAD

**Issue by sozanne** [nmdp-bioinformatics/dash#19]
In a research perspective we (NMDP) has received data from Histogenetics that specified phasing in order to resolve ambiguity.  The attributes that were part of the .9.3 spec are no longer part of the .9.5 spec (format attribute on targeted-region where format contains some combination of loci and exons.

Note: this is in reference to the email from Seonghan Kim on April 11, 2014.

**Comment by mheuer-nmdp** [comment]
Fixed in HML version 1.0 with phase-set attribute, see https://github.com/nmdp-bioinformatics/hml/issues/26
