### ISSUE TITLE
Consensus Sequences:  IMGT alignments

### ISSUE THREAD

**Issue by jpollacknmdp** [nmdp-bioinformatics/dash#24]
-          Alleles in IMGT show dashes at places for which a –rare- allele has an insertion. In the consensus-sequence, describing the two alleles in a regions this can be covered in two ways
o   Leave the dashes in the nucleotide sequence to maintain the alignment with the IMGT. We think this is confusing and not desirable
o   Remove the dashes. This may result in two consensus sequences, for each allele one, which have different lengths. This requires a feature-table for each allele instead of for each phased region. -- Erik Rosemuller

**Comment by mheuer-nmdp** [comment]
Fixed in HML version 1.0, see https://github.com/nmdp-bioinformatics/hml/issues/26
