### ISSUE TITLE
Novel Polymorphisms:  How to define 'unreferenced regions'?

### ISSUE THREAD

**Issue by jpollacknmdp** [nmdp-bioinformatics/dash#26]
In case of alleles for which parts are not available in the IMGT, are these regions considered ‘unreferenced regions’?
o   What is the best section to describe if results included matching regions not published before in the alleles involved? -- Erik Rosemuller

**Comment by mheuer-nmdp** [comment]
Fixed in HML version 1.0 with reference availability attribute
https://github.com/nmdp-bioinformatics/hml/blob/master/spec/hml/1.0/hml-1.0.xsd#L1278

See https://github.com/nmdp-bioinformatics/hml/issues/26
