### ISSUE TITLE
HML Spec: 'Typing-Method' attribute ref-id versus test-id/test-id-source

### ISSUE THREAD

**Issue by dvaliga** [nmdp-bioinformatics/dash#5]
HML beta spec: Attributes for child nodes inheriting from 'typing-method' (sso, ssp, sbt-sanger, sbt-ngs) had contained a locus attribute and then a required pair of attributes for test-id/test-id-source.  This seemed reasonable, but broke the ID/IDREF relationship for typings that reference a list of typing-test-names/probe tests/kits ('ref-id' was originally just a string value for the test-id-source attribute).  To maintain document integrity, had to make ref-id an optional attribute of type "xs:IDREF" and also make test-id and test-id-source optional.  This is a bit ugly and could use some cleanup, but no obvious solution that meets all needs.

**Comment by mheuer-nmdp** [comment]
Fixed in HML version 1.0, see https://github.com/nmdp-bioinformatics/hml/issues/26
