### ISSUE TITLE
HML Spec: allele-db / allele-version / nomenclature

### ISSUE THREAD

**Issue by dvaliga** [nmdp-bioinformatics/dash#6]
The HML 'interpretation' node currently has two optional fields called allele-db and allele-version.  The format of these is unspecified.  What would DaSH attendees expect to put in these fields?  

It has also been suggested that allele-db and allele-version be combined into a single attribute called 'nomenclature'.  Would that make sense?  What format would be expected?  

Allele-db/allele-version/nomenclature really only applies to 3 of the 4 children of interpretation.  In addition it is used when looking at typings (sso/ssp/ngs/sanger).  Should these attributes be moved to the top-level 'typing' node and apply to all methods/interpretations under each typing?  Should they be moved to specific interpretation child nodes and made required instead of optional?

**Comment by mheuer-nmdp** [comment]
Fixed in HML version 1.0, see https://github.com/nmdp-bioinformatics/hml/issues/26
